### ISSUE TITLE
/clip Documentation?

### ISSUE THREAD

**Issue by mksbamford** [aws-samples/amazon-ivs-clip-web-demo#1]
I can't find any documentation for /clip, is it a new endpoint? Can it store more than 30 seconds?

**Comment by coral** [comment]
@mksbamford The /clip endpoint is created by the Go lambda which is created by the CDK wrapper. You're essentially hosting the "/clip" infrastructure yourself here but it's all orchestrated by CDK.

Right now it can only grab the last 30 seconds.
